import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0F9FF",
  },
  header: {
    backgroundColor: "#3B82F6",
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "ios" ? 60 : 40,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: {
    flex: 1,
  },
  greeting: {
    fontSize: 20,
    fontWeight: "600",
    color: "white",
    marginBottom: 4,
  },
  date: {
    fontSize: 14,
    color: "#BFDBFE",
  },
  settingsButton: {
    padding: 12,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 16,
  },
  settingsIcon: {
    fontSize: 20,
  },
  content: {
    flex: 1,
  },
  trackerContainer: {
    padding: 24,
    paddingTop: 32,
  },
  trackerCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 32,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
    position: "relative",
    overflow: "visible",
  },
  waterDrop: {
    position: "absolute",
    top: -25,
    zIndex: 10,
  },
  dropIcon: {
    fontSize: 28,
  },
  circularTracker: {
    alignItems: "center",
    marginBottom: 24,
  },
  outerCircle: {
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "#F8FAFC",
    borderWidth: 6,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  waterLevel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#3B82F6",
    overflow: "hidden",
  },
  wave1: {
    position: "absolute",
    top: -8,
    left: -30,
    right: -30,
    height: 16,
    backgroundColor: "#60A5FA",
    borderRadius: 8,
    opacity: 0.7,
  },
  wave2: {
    position: "absolute",
    top: -4,
    left: -25,
    right: -25,
    height: 12,
    backgroundColor: "#93C5FD",
    borderRadius: 6,
    opacity: 0.5,
  },
  centerContent: {
    alignItems: "center",
    zIndex: 2,
    backgroundColor: "transparent",
  },
  currentAmount: {
    fontSize: 42,
    fontWeight: "bold",
    color: "#1E293B",
  },
  unit: {
    fontSize: 18,
    color: "#64748B",
    marginTop: -4,
  },
  goalContainer: {
    alignItems: "center",
    marginTop: 12,
  },
  goalText: {
    fontSize: 14,
    color: "#64748B",
  },
  percentage: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#3B82F6",
    marginTop: 4,
  },
  motivationalText: {
    fontSize: 17,
    color: "#3B82F6",
    textAlign: "center",
    fontWeight: "600",
    marginBottom: 8,
    lineHeight: 24,
  },
  remainingText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
  },
  quickAddContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 16,
  },
  quickAddGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  quickAddButton: {
    width: "30%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#E0F2FE",
  },
  quickAddIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  quickAddAmount: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3B82F6",
  },
  progressContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  statCard: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    marginHorizontal: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  statIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1E293B",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#64748B",
  },
  entriesContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  entryItem: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  entryLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  entryIconContainer: {
    width: 40,
    height: 40,
    backgroundColor: "#EBF4FF",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  entryIcon: {
    fontSize: 18,
  },
  entryAmount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E293B",
  },
  entryTime: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
  entryType: {
    fontSize: 14,
    color: "#3B82F6",
    fontWeight: "600",
  },
  customAddButton: {
    marginHorizontal: 24,
    backgroundColor: "#3B82F6",
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#3B82F6",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginBottom: 24,
  },
  customAddIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  customAddText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  achievementBadge: {
    marginHorizontal: 24,
    backgroundColor: "#10B981",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#10B981",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginBottom: 24,
  },
  achievementIcon: {
    fontSize: 48,
    marginBottom: 8,
  },
  achievementTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    marginBottom: 4,
  },
  achievementSubtitle: {
    fontSize: 14,
    color: "#A7F3D0",
  },
  bottomSpacer: {
    height: 24,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    width: "85%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1E293B",
    marginBottom: 8,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 20,
  },
  modalInput: {
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 18,
    color: "#1E293B",
    textAlign: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
  },
  modalButtonCancel: {
    backgroundColor: "#F1F5F9",
    marginRight: 8,
  },
  modalButtonAdd: {
    backgroundColor: "#3B82F6",
    marginLeft: 8,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },
  modalButtonTextCancel: {
    color: "#334155",
  },
});
